### ISSUE TITLE
README fixes

### ISSUE THREAD

**Issue by phipac** [kd7lxl/aprs2netportal#1]
sudo apt-get install nginx python-pip python-virtualenv python-dev git-core libpq-dev postgresql postfix
(typo: libpq-dev)

Install Python Dependencies
(env)portal@t2dev:/var/www/aprs2netportal$ pip install –U Django==1.6
(env)portal@t2dev:/var/www/aprs2netportal$ pip install south psycopg2 
(issue: force install Django v1.6)

Initialize Database
(env)portal@t2dev:/var/www/aprs2netportal$ ./manage.py syncdb
(env)portal@t2dev:/var/www/aprs2netportal$ ./manage.py migrate
(issue: change ./manage to ./manage.py)

Test Django
(env)portal@t2dev:/var/www/aprs2netportal$ ./manage.py runserver 0.0.0.0:8000
(issue: change ./manage to ./manage.py)

**Comment by kd7lxl** [comment]
Fixed in 054a754
